// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#nullable disable

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
// Here because of a mistake. Shit fix.
using intptr_t = nint;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

#nullable disable

namespace Steamworks {
	// Here because of a mistake. Shit fix.
	using intptr_t = nint;

	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct HHTMLBrowser : System.IEquatable<HHTMLBrowser>, System.IComparable<HHTMLBrowser> {
		public static readonly HHTMLBrowser Invalid = new HHTMLBrowser(0);
		public uint m_HHTMLBrowser;

		public HHTMLBrowser(uint value) {
			m_HHTMLBrowser = value;
		}

		public override string ToString() {
			return m_HHTMLBrowser.ToString();
		}

		public override bool Equals(object other) {
			return other is HHTMLBrowser && this == (HHTMLBrowser)other;
		}

		public override int GetHashCode() {
			return m_HHTMLBrowser.GetHashCode();
		}

		public static bool operator ==(HHTMLBrowser x, HHTMLBrowser y) {
			return x.m_HHTMLBrowser == y.m_HHTMLBrowser;
		}

		public static bool operator !=(HHTMLBrowser x, HHTMLBrowser y) {
			return !(x == y);
		}

		public static explicit operator HHTMLBrowser(uint value) {
			return new HHTMLBrowser(value);
		}

		public static explicit operator uint(HHTMLBrowser that) {
			return that.m_HHTMLBrowser;
		}

		public bool Equals(HHTMLBrowser other) {
			return m_HHTMLBrowser == other.m_HHTMLBrowser;
		}

		public int CompareTo(HHTMLBrowser other) {
			return m_HHTMLBrowser.CompareTo(other.m_HHTMLBrowser);
		}
	}
}

#endif // !DISABLESTEAMWORKS
