// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#nullable disable

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
// Here because of a mistake. Shit fix.
using intptr_t = nint;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

#nullable disable

namespace Steamworks {
	// Here because of a mistake. Shit fix.
	using intptr_t = nint;

	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct HTTPCookieContainerHandle : System.IEquatable<HTTPCookieContainerHandle>, System.IComparable<HTTPCookieContainerHandle> {
		public static readonly HTTPCookieContainerHandle Invalid = new HTTPCookieContainerHandle(0);
		public uint m_HTTPCookieContainerHandle;

		public HTTPCookieContainerHandle(uint value) {
			m_HTTPCookieContainerHandle = value;
		}

		public override string ToString() {
			return m_HTTPCookieContainerHandle.ToString();
		}

		public override bool Equals(object other) {
			return other is HTTPCookieContainerHandle && this == (HTTPCookieContainerHandle)other;
		}

		public override int GetHashCode() {
			return m_HTTPCookieContainerHandle.GetHashCode();
		}

		public static bool operator ==(HTTPCookieContainerHandle x, HTTPCookieContainerHandle y) {
			return x.m_HTTPCookieContainerHandle == y.m_HTTPCookieContainerHandle;
		}

		public static bool operator !=(HTTPCookieContainerHandle x, HTTPCookieContainerHandle y) {
			return !(x == y);
		}

		public static explicit operator HTTPCookieContainerHandle(uint value) {
			return new HTTPCookieContainerHandle(value);
		}

		public static explicit operator uint(HTTPCookieContainerHandle that) {
			return that.m_HTTPCookieContainerHandle;
		}

		public bool Equals(HTTPCookieContainerHandle other) {
			return m_HTTPCookieContainerHandle == other.m_HTTPCookieContainerHandle;
		}

		public int CompareTo(HTTPCookieContainerHandle other) {
			return m_HTTPCookieContainerHandle.CompareTo(other.m_HTTPCookieContainerHandle);
		}
	}
}

#endif // !DISABLESTEAMWORKS
