// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#nullable disable

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
// Here because of a mistake. Shit fix.
using intptr_t = nint;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

#nullable disable

namespace Steamworks {
	// Here because of a mistake. Shit fix.
	using intptr_t = nint;

	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct SteamItemDef_t : System.IEquatable<SteamItemDef_t>, System.IComparable<SteamItemDef_t> {
		public int m_SteamItemDef;

		public SteamItemDef_t(int value) {
			m_SteamItemDef = value;
		}

		public override string ToString() {
			return m_SteamItemDef.ToString();
		}

		public override bool Equals(object other) {
			return other is SteamItemDef_t && this == (SteamItemDef_t)other;
		}

		public override int GetHashCode() {
			return m_SteamItemDef.GetHashCode();
		}

		public static bool operator ==(SteamItemDef_t x, SteamItemDef_t y) {
			return x.m_SteamItemDef == y.m_SteamItemDef;
		}

		public static bool operator !=(SteamItemDef_t x, SteamItemDef_t y) {
			return !(x == y);
		}

		public static explicit operator SteamItemDef_t(int value) {
			return new SteamItemDef_t(value);
		}

		public static explicit operator int(SteamItemDef_t that) {
			return that.m_SteamItemDef;
		}

		public bool Equals(SteamItemDef_t other) {
			return m_SteamItemDef == other.m_SteamItemDef;
		}

		public int CompareTo(SteamItemDef_t other) {
			return m_SteamItemDef.CompareTo(other.m_SteamItemDef);
		}
	}
}

#endif // !DISABLESTEAMWORKS
