// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

namespace Steamworks {
	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct ScreenshotHandle : System.IEquatable<ScreenshotHandle>, System.IComparable<ScreenshotHandle> {
		public static readonly ScreenshotHandle Invalid = new ScreenshotHandle(0);
		public uint m_ScreenshotHandle;

		public ScreenshotHandle(uint value) {
			m_ScreenshotHandle = value;
		}

		public override string ToString() {
			return m_ScreenshotHandle.ToString();
		}

		public override bool Equals(object other) {
			return other is ScreenshotHandle && this == (ScreenshotHandle)other;
		}

		public override int GetHashCode() {
			return m_ScreenshotHandle.GetHashCode();
		}

		public static bool operator ==(ScreenshotHandle x, ScreenshotHandle y) {
			return x.m_ScreenshotHandle == y.m_ScreenshotHandle;
		}

		public static bool operator !=(ScreenshotHandle x, ScreenshotHandle y) {
			return !(x == y);
		}

		public static explicit operator ScreenshotHandle(uint value) {
			return new ScreenshotHandle(value);
		}

		public static explicit operator uint(ScreenshotHandle that) {
			return that.m_ScreenshotHandle;
		}

		public bool Equals(ScreenshotHandle other) {
			return m_ScreenshotHandle == other.m_ScreenshotHandle;
		}

		public int CompareTo(ScreenshotHandle other) {
			return m_ScreenshotHandle.CompareTo(other.m_ScreenshotHandle);
		}
	}
}

#endif // !DISABLESTEAMWORKS
