// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
// Here because of a mistake. Shit fix.
using intptr_t = nint;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

namespace Steamworks {
	// Here because of a mistake. Shit fix.
	using intptr_t = nint;
	
	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct AppId_t : System.IEquatable<AppId_t>, System.IComparable<AppId_t> {
		public static readonly AppId_t Invalid = new AppId_t(0x0);
		public uint m_AppId;

		public AppId_t(uint value) {
			m_AppId = value;
		}

		public override string ToString() {
			return m_AppId.ToString();
		}

		public override bool Equals(object other) {
			return other is AppId_t && this == (AppId_t)other;
		}

		public override int GetHashCode() {
			return m_AppId.GetHashCode();
		}

		public static bool operator ==(AppId_t x, AppId_t y) {
			return x.m_AppId == y.m_AppId;
		}

		public static bool operator !=(AppId_t x, AppId_t y) {
			return !(x == y);
		}

		public static explicit operator AppId_t(uint value) {
			return new AppId_t(value);
		}

		public static explicit operator uint(AppId_t that) {
			return that.m_AppId;
		}

		public bool Equals(AppId_t other) {
			return m_AppId == other.m_AppId;
		}

		public int CompareTo(AppId_t other) {
			return m_AppId.CompareTo(other.m_AppId);
		}
	}
}

#endif // !DISABLESTEAMWORKS
