// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2022 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file has been modified by Xan's Workshop for integration into Godot.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#nullable disable

#if GODOT_WINDOWS
#define STEAMWORKS_WIN
#elif GODOT_LINUXBSD || GODOT_OSX
#define STEAMWORKS_LIN_OSX
#endif

#if !(UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX || UNITY_STANDALONE_OSX || UNITY_ANDROID || STEAMWORKS_WIN || STEAMWORKS_LIN_OSX)
	#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

using System.Runtime.InteropServices;
// Here because of a mistake. Shit fix.
using intptr_t = nint;

#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation
#pragma warning disable IDE0130 // Namespace does not match folder structure
#pragma warning disable CS1591 // Missing documentation

#nullable disable

namespace Steamworks {
	// Here because of a mistake. Shit fix.
	using intptr_t = nint;

	[System.Serializable]
#if THE_CONSERVATORY
	[Star3D.Security.SecurityDeny(Star3D.Security.Capability.Patching)]
#endif
	public struct DepotId_t : System.IEquatable<DepotId_t>, System.IComparable<DepotId_t> {
		public static readonly DepotId_t Invalid = new DepotId_t(0x0);
		public uint m_DepotId;

		public DepotId_t(uint value) {
			m_DepotId = value;
		}

		public override string ToString() {
			return m_DepotId.ToString();
		}

		public override bool Equals(object other) {
			return other is DepotId_t && this == (DepotId_t)other;
		}

		public override int GetHashCode() {
			return m_DepotId.GetHashCode();
		}

		public static bool operator ==(DepotId_t x, DepotId_t y) {
			return x.m_DepotId == y.m_DepotId;
		}

		public static bool operator !=(DepotId_t x, DepotId_t y) {
			return !(x == y);
		}

		public static explicit operator DepotId_t(uint value) {
			return new DepotId_t(value);
		}

		public static explicit operator uint(DepotId_t that) {
			return that.m_DepotId;
		}

		public bool Equals(DepotId_t other) {
			return m_DepotId == other.m_DepotId;
		}

		public int CompareTo(DepotId_t other) {
			return m_DepotId.CompareTo(other.m_DepotId);
		}
	}
}

#endif // !DISABLESTEAMWORKS
